// ═══════════════════════════════════════════
// DATA
// ═══════════════════════════════════════════
const GL=[
  {id:'b10',code:'B-10',color:'#007d8a',title:'Third-Party Risk Management',eff:'Effective May 1, 2024',domains:[
    {id:'b10_gov',title:'Governance & Accountability',qs:[
      {id:'q_b10_g1',ref:'B-10 §2.1',why:'Board-level accountability is the first test in any OSFI supervisory review — without it, all downstream controls are considered ad hoc.',text:'Is there a documented, enterprise-wide TPRM framework with clear ownership assigned to a senior executive?',simple:true,scenarios:['all','tprm']},
      {id:'q_b10_g2',ref:'B-10 §2.2',why:'OSFI expects 3LoD accountability to be explicit and operational, not theoretical — a common finding is that the second line is not meaningfully challenging the first.',text:'Are roles and responsibilities for third-party risk clearly defined across the first, second, and third lines of defence?',scenarios:['all','tprm']},
      {id:'q_b10_g3',ref:'B-10 §2.3',why:'Aggregate concentration risk is a top supervisory concern — board reporting must go beyond individual vendor performance to systemic exposure.',text:'Does the Board or a delegated risk committee receive regular reporting on aggregate third-party risk exposure and concentration risk?',scenarios:['all','tprm']},
    ]},
    {id:'b10_risk',title:'Risk Identification & Assessment',qs:[
      {id:'q_b10_r1',ref:'B-10 §3.1',why:'OSFI has found that most institutions have incomplete inventories — sub-contractors and intra-group arrangements are frequently missed.',text:'Is a comprehensive, up-to-date inventory of all third-party arrangements maintained, including sub-contractors and intra-group arrangements?',simple:true,scenarios:['all','tprm','cloud']},
      {id:'q_b10_r2',ref:'B-10 §3.2',why:'Proportionality requires criticality classification — without it, due diligence and monitoring resources are misallocated.',text:'Is a risk-based criticality classification applied to all third-party arrangements, proportionate to operational and financial impact?',scenarios:['all','tprm']},
      {id:'q_b10_r3',ref:'B-10 §3.3',why:'Concentration risk is OSFI\'s primary systemic concern — a single hyperscaler outage affecting multiple critical operations is the scenario being stress-tested.',text:'Are concentration risk exposures — single vendor, geography, or technology — formally assessed and reported at both entity and systemic levels?',scenarios:['all','tprm','cloud']},
    ]},
    {id:'b10_due',title:'Due Diligence & Contracting',qs:[
      {id:'q_b10_d1',ref:'B-10 §4.1',why:'Enhanced due diligence is a regulatory baseline for critical arrangements — performing it post-onboarding is a supervisory finding.',text:'Are enhanced due diligence requirements applied to high-risk and critical third-party arrangements prior to engagement?',scenarios:['all','tprm']},
      {id:'q_b10_d2',ref:'B-10 §4.2',why:'OSFI minimum contract clauses are now explicit — right to audit and exit rights are non-negotiable for critical arrangements.',text:'Do contracts with critical third parties include OSFI minimum clauses: right to audit, performance standards, incident notification, and exit rights?',scenarios:['all','tprm','cloud']},
      {id:'q_b10_d3',ref:'B-10 §4.3',why:'Cloud hyperscalers present a unique challenge — OSFI acknowledges standard terms cannot always be obtained and expects compensating controls.',text:'Is there a process for managing arrangements where standard contractual terms cannot be obtained, such as with systemic cloud providers?',scenarios:['all','tprm','cloud']},
    ]},
    {id:'b10_mon',title:'Ongoing Monitoring & Exit Planning',qs:[
      {id:'q_b10_m1',ref:'B-10 §5.1',why:'Ongoing monitoring frequency must be risk-based — monitoring critical cloud arrangements quarterly while monitoring minor vendors annually is expected.',text:'Are ongoing performance monitoring and risk reassessment processes in place, with frequency calibrated to arrangement criticality?',scenarios:['all','tprm']},
      {id:'q_b10_m2',ref:'B-10 §5.2',why:'Exit plans and substitutability assessments are tested during supervisory reviews — the absence of credible exit plans for critical vendors is a recurring finding.',text:'Are documented exit plans and substitutability assessments in place for all critical third-party arrangements?',scenarios:['all','tprm','resilience']},
      {id:'q_b10_m3',ref:'B-10 §5.3',why:'B-10 and B-13 are explicitly interconnected — technology and cyber risks from third parties must be managed within the B-13 framework, not separately.',text:'Are technology and cyber risks arising from third-party arrangements specifically addressed and integrated with B-13 controls?',scenarios:['all','tprm','cloud']},
    ]},
  ]},
  {id:'b13',code:'B-13',color:'#009aaa',title:'Technology & Cyber Risk Management',eff:'Effective Jan 1, 2024',domains:[
    {id:'b13_gov',title:'Governance & Risk Management Framework',qs:[
      {id:'q_b13_g1',ref:'B-13 P1',why:'Without clear CIO/CISO accountability and resources, technology risk governance becomes a compliance exercise rather than an operational function.',text:'Has senior management assigned clear accountability for technology and cyber risk, with defined CTO/CIO/CISO roles, adequate authority and resources?',simple:true,scenarios:['all','cloud']},
      {id:'q_b13_g2',ref:'B-13 P3',why:'The B-13 RMF must be integrated with the enterprise RMF — a standalone technology risk framework that does not feed into enterprise reporting is a gap.',text:'Is a Technology and Cyber Risk Management Framework formally documented, aligned with the enterprise RMF, and regularly reviewed?',scenarios:['all','cloud']},
      {id:'q_b13_g3',ref:'B-13 P4',why:'Technology architecture governance is foundational to IT asset visibility — without it, the inventory required by B-13 cannot be maintained.',text:'Does the institution maintain a technology architecture framework governing design, implementation, and evolution of technology assets?',scenarios:['all','cloud']},
    ]},
    {id:'b13_ops',title:'Technology Operations & Resilience',qs:[
      {id:'q_b13_o1',ref:'B-13 P5–7',why:'IT asset inventory completeness is a precondition for defining RTOs and RPOs — OSFI examines whether RTO/RPO are set for all critical assets, not just selected systems.',text:'Is there a comprehensive, current inventory of critical technology assets with defined recovery time and point objectives?',simple:true,scenarios:['all','cloud','resilience']},
      {id:'q_b13_o2',ref:'B-13 P8–9',why:'SDLC security gates prevent the accumulation of technical debt and vulnerability exposure — their absence is a common B-13 supervisory finding.',text:'Does the SDLC process incorporate security risk assessments, control gates, and change management aligned with the institution\'s risk appetite?',scenarios:['all','cloud','ai']},
      {id:'q_b13_o3',ref:'B-13 P13',why:'DR testing must cover severe-but-plausible scenarios — tabletop exercises without live-systems validation do not satisfy the B-13 standard.',text:'Are disaster recovery scenarios regularly tested against severe-but-plausible disruptions, with results reviewed by senior management?',scenarios:['all','cloud','resilience']},
    ]},
    {id:'b13_cyber',title:'Cyber Security',qs:[
      {id:'q_b13_c1',ref:'B-13 P14',why:'Cyber strategy must be aligned to the technology strategy — a cyber program that operates independently of technology architecture is a structural gap.',text:'Is a cyber security strategy documented, covering threat intelligence, identity management, and defence-in-depth controls?',simple:true,scenarios:['all','cloud']},
      {id:'q_b13_c2',ref:'B-13 P15',why:'Penetration testing and red team exercises are now expected annually for institutions of material size — quarterly for systemically important institutions.',text:'Are threat and vulnerability management processes in place, including penetration testing, red team exercises, and timely remediation tracking?',scenarios:['all','cloud']},
      {id:'q_b13_c3',ref:'B-13 P16–17',why:'OSFI\'s Technology and Cyber Incident Reporting Advisory sets explicit timelines — institutions must demonstrate response capability, not just plan existence.',text:'Is there a documented, tested cyber incident response plan meeting OSFI\'s Technology and Cyber Incident Reporting Advisory timelines?',scenarios:['all','cloud','resilience']},
      {id:'q_b13_c4',ref:'B-13 P17',why:'Security awareness training must be role-based — generic annual training does not satisfy the B-13 expectation for technical and privileged access roles.',text:'Is cybersecurity embedded within project management and SDLC, with staff receiving adequate, role-based security awareness training?',scenarios:['all']},
    ]},
  ]},
  {id:'e21',code:'E-21',color:'#5a9ea8',title:'Operational Risk & Resilience',eff:'Effective Aug 22, 2024 (phased to Sep 2026)',domains:[
    {id:'e21_gov',title:'Governance & Risk Appetite',qs:[
      {id:'q_e21_g1',ref:'E-21 §1',why:'Risk appetite must be operational and monitored — a risk appetite statement that is not linked to specific thresholds is a supervisory finding under E-21.',text:'Does the Board-approved risk appetite explicitly address operational risk, with defined risk limits cascaded to business lines and monitored against thresholds?',simple:true,scenarios:['all','resilience']},
      {id:'q_e21_g2',ref:'E-21 §1',why:'A consistent risk taxonomy is the foundation for cross-guideline integration — inconsistent categorisation prevents aggregation and creates reporting blind spots.',text:'Is a formal operational risk taxonomy used consistently across lines of business and risk reporting?',scenarios:['all','resilience']},
      {id:'q_e21_g3',ref:'E-21 §2',why:'RCSA, KRI, and scenario analysis outputs must inform capital decisions — disconnected ORM tools that do not feed into strategic decision-making are insufficient.',text:'Are standard ORM tools — RCSAs, KRIs, loss event data, scenario analysis — deployed enterprise-wide, with outputs informing capital and strategic decisions?',scenarios:['all','resilience']},
    ]},
    {id:'e21_res',title:'Operational Resilience',qs:[
      {id:'q_e21_r1',ref:'E-21 §3.1',why:'Critical operation mapping is the foundational E-21 requirement — OSFI expects end-to-end dependency mapping including third parties, not just internal systems.',text:'Have critical operations been identified with documented mapping of all internal and external dependencies — people, technology, facilities, data, and third parties?',simple:true,scenarios:['all','resilience','cloud','tprm']},
      {id:'q_e21_r2',ref:'E-21 §3.2',why:'Disruption tolerances must reflect what the institution can actually deliver — tolerances set without stress testing are routinely invalidated under examination.',text:'Are tolerances for disruption formally established and approved for each critical operation, reflecting maximum acceptable downtime across severe-but-plausible scenarios?',scenarios:['all','resilience']},
      {id:'q_e21_r3',ref:'E-21 §3.3',why:'Live-systems scenario testing is the E-21 gold standard — tabletop exercises demonstrate planning capability, not operational resilience.',text:'Is scenario testing conducted regularly — tabletop, simulation, live-systems — to validate ability to remain within disruption tolerances, including third-party participation?',scenarios:['all','resilience','tprm']},
    ]},
    {id:'e21_bcm',title:'Business Continuity & Crisis Management',qs:[
      {id:'q_e21_b1',ref:'E-21 §4.1',why:'BCPs must be tested and current — plans that have not been updated since a material change to dependencies are treated as absent by OSFI examiners.',text:'Are Business Continuity Plans maintained for all critical operations, regularly tested, and updated to reflect changes in dependencies?',scenarios:['all','resilience']},
      {id:'q_e21_b2',ref:'E-21 §4.2',why:'Crisis management capability is tested through exercises — the absence of an annual crisis management exercise is a standard E-21 finding.',text:'Is there a Crisis Management framework with defined escalation protocols, communication plans, and a crisis team exercised at least annually?',scenarios:['all','resilience']},
      {id:'q_e21_b3',ref:'E-21 §4.3',why:'Operational risk implications of change are frequently overlooked — change management processes that do not include operational risk assessment create accumulating exposure.',text:'Is there a formal change management process that assesses operational risk implications before material changes to people, processes, systems, or third-party arrangements?',scenarios:['all','resilience']},
    ]},
    {id:'e21_data',title:'Data Risk Management',qs:[
      {id:'q_e21_d1',ref:'E-21 §4.4',why:'Data risk management is explicitly addressed in E-21 — the absence of a data classification scheme is a direct E-21 finding, not just a data governance gap.',text:'Does the institution have a data risk management program with defined roles, a data classification scheme, and data quality standards?',scenarios:['all','resilience','ai']},
      {id:'q_e21_d2',ref:'E-21 §4.4',why:'BCBS 239 principles underpin E-21 data aggregation requirements — institutions that cannot produce accurate risk data under stress are considered operationally resilient on paper only.',text:'Are data aggregation and reporting capabilities sufficient to produce accurate, timely risk information for management and regulatory reporting, including under stress scenarios?',scenarios:['all','resilience']},
    ]},
  ]},
  {id:'e23',code:'E-23',color:'#3d7f87',title:'Model Risk & AI Governance',eff:'Effective May 1, 2027',domains:[
    {id:'e23_gov',title:'Governance & MRM Framework',qs:[
      {id:'q_e23_g1',ref:'E-23 §2.1',why:'An enterprise-wide MRM framework is the foundational E-23 requirement — institutions that manage model risk at the business unit level will not meet the E-23 standard.',text:'Is there a Board/senior management-approved, enterprise-wide Model Risk Management framework documented and integrated into the overall risk governance structure?',simple:true,scenarios:['all','ai']},
      {id:'q_e23_g2',ref:'E-23 §2.2',why:'Functional separation between model developers and validators is a minimum E-23 requirement — self-validation by model owners is explicitly excluded.',text:'Are roles — Model Owner, Developer, Independent Reviewer — clearly defined with appropriate functional separation and documented accountability?',scenarios:['all','ai']},
      {id:'q_e23_g3',ref:'E-23 §2.3',why:'Proportionality under E-23 means that high-risk and AI models require multi-disciplinary governance — technical and risk review is not sufficient alone.',text:'Does MRM governance scale proportionately to model complexity and risk, with multi-disciplinary teams engaged at appropriate lifecycle stages?',scenarios:['all','ai']},
    ]},
    {id:'e23_inv',title:'Model Inventory & Risk Rating',qs:[
      {id:'q_e23_i1',ref:'E-23 P2.1',why:'The scope of E-23 is broad — AI tools, vendor models, and analytical models used in decision-making must all be inventoried, not just formally built quantitative models.',text:'Does the institution maintain a comprehensive model inventory capturing all models with non-negligible risk, including AI/ML models and third-party sourced models?',simple:true,scenarios:['all','ai','tprm']},
      {id:'q_e23_i2',ref:'E-23 P2.2',why:'Risk rating must be multi-dimensional under E-23 — a rating based only on financial impact will miss autonomy and customer fairness dimensions for AI models.',text:'Is a model risk rating approach implemented using both quantitative (financial/operational impact) and qualitative factors (complexity, autonomy, customer impact)?',scenarios:['all','ai']},
      {id:'q_e23_i3',ref:'E-23 P2.2',why:'Consistency of risk ratings across business units is a supervisory test — inconsistent ratings for similar models indicate governance gaps.',text:'Are risk ratings consistently applied across business units and reviewed when model usage materially changes, with enhanced scrutiny for high-risk and AI models?',scenarios:['all','ai']},
    ]},
    {id:'e23_life',title:'Model Lifecycle Governance',qs:[
      {id:'q_e23_l1',ref:'E-23 §3',why:'Lifecycle documentation must cover all stages — models that are deployed without formal approval or decommissioned without review create untracked risk exposure.',text:'Are documented policies and procedures in place for each stage of the model lifecycle: design, development, testing, approval, deployment, monitoring, and decommissioning?',scenarios:['all','ai']},
      {id:'q_e23_l2',ref:'E-23 §3.3',why:'Independent validation is the core E-23 control — validation by technically proficient staff who are functionally separate from developers is non-negotiable.',text:'Is independent model validation conducted by personnel functionally separate from developers, with scope and frequency proportionate to model risk rating?',scenarios:['all','ai']},
      {id:'q_e23_l3',ref:'E-23 §3.4',why:'Ongoing monitoring must detect model deterioration before it creates losses or regulatory exposure — monitoring that only triggers review after failure is insufficient.',text:'Are ongoing model performance monitoring and periodic review processes in place, with material deterioration triggering escalation and re-validation?',scenarios:['all','ai']},
    ]},
    {id:'e23_ai',title:'AI/ML & Third-Party Model Oversight',qs:[
      {id:'q_e23_a1',ref:'E-23 §4',why:'AI models carry unique risks — explainability, bias, and autonomy require specific governance controls that standard model risk frameworks do not cover.',text:'Are AI and machine learning models subject to enhanced governance addressing explainability, bias assessment, data quality, and autonomy risk?',simple:true,scenarios:['all','ai']},
      {id:'q_e23_a2',ref:'E-23 §4.2 / B-10',why:'Third-party model residual risk is a convergence point for B-10 and E-23 — the institution cannot transfer MRM responsibility to the vendor.',text:'Does the institution assess and manage residual risks from third-party model providers, including vendors without MRM-equivalent standards?',scenarios:['all','ai','tprm']},
      {id:'q_e23_a3',ref:'E-23 §4.3',why:'AI ethics and fairness are explicit in E-23 — bias testing for customer-facing models is not optional, and the absence of a documented process will be a supervisory finding.',text:'Is there a documented AI ethics and fairness consideration process, with customer-facing AI models subject to bias testing before deployment?',scenarios:['all','ai']},
    ]},
  ]},
];

const ML=['','Initial','Developing','Defined','Managed','Optimizing'];
const SC={0:'var(--muted)',1:'var(--s1)',2:'var(--s2)',3:'var(--s3)',4:'var(--s4)',5:'var(--s5)'};

const MF_TEXT={
  1:['Foundational gap — this control requires immediate design and ownership assignment before the next supervisory review.','Ad-hoc posture — significant remediation investment required; this is a likely supervisory finding if unaddressed.'],
  2:['Developing — processes exist but are inconsistently applied. Standardization and enterprise-wide enforcement are the priority.','Emerging capability — strong foundation present but gaps in consistency and measurement create residual exam exposure.'],
  3:['Defined — documented and standardized, but measurement, automation, and cross-domain integration need strengthening.','Defined maturity — solid baseline. The gap is moving from defined to managed: KPIs, dashboards, and continuous monitoring.'],
  4:['Managed — strong posture with measurable performance. Focus on automation and reducing manual control burden.','Strong control — measured and monitored. Optimization and proactive supervisory engagement are the next horizon.'],
  5:['Optimizing — best-in-class maturity. Sustain through continuous improvement and automated evidence generation.','Leading practice — fully embedded, proactive and continuously improved. Excellent supervisory evidence foundation.'],
};

const SIMS_DATA=[
  {risks:[{code:'B-10',text:'Hyperscaler dependency triggers concentration risk assessment; contracts must include right to audit and exit rights'},{code:'B-13',text:'Cloud infrastructure requires IT asset visibility, cyber control mapping, and DR scenario testing'},{code:'E-21',text:'Payment operation is almost certainly critical — disruption tolerances must be defined and tested with the provider'},{code:'E-23',text:'Any AI-based fraud detection or routing logic requires model inventory entry, risk rating, and validation'}],implications:['A single cloud outage may simultaneously trigger B-10 incident reporting, B-13 technology notification, and E-21 disruption tolerance breach — across three separate regulatory channels.','Aggregate concentration exposure may not be visible in any single risk register if the same cloud provider supports multiple critical operations.']},
  {risks:[{code:'B-10',text:'If AI engine is third-party sourced, full TPRM obligations apply including sub-contractor and fourth-party visibility'},{code:'B-13',text:'Technology underpinning the AI engine must be in the IT asset inventory with defined resilience and recovery requirements'},{code:'E-21',text:'Lending decisions are a critical operation — AI degradation or failure must fall within the disruption tolerance framework'},{code:'E-23',text:'Core E-23 obligation: model inventory, risk rating, independent validation, bias testing, lifecycle governance, monitoring'}],implications:['Most institutions have deployed AI in lending ahead of formal MRM frameworks — creating a retroactive inventory and validation problem under E-23.','If the AI model is vendor-supplied, OSFI expects the institution to manage residual MRM risk from vendors who do not meet E-23 standards.']},
  {risks:[{code:'B-10',text:'Data provider is a third-party arrangement — must be inventoried, risk-rated, and subject to due diligence proportionate to criticality'},{code:'B-13',text:'Data pipeline integrity is a technology asset — requires data quality controls and resilience against provider disruption'},{code:'E-21',text:'Data loss or corruption is an E-21 disruption threat — BCPs must address data recovery and substitution'},{code:'E-23',text:'External data feeding internal models is in scope — data governance and quality controls must be in the model inventory'}],implications:['The data-to-model-to-decision chain is rarely traceable end-to-end — creating an audit exposure that spans all four guidelines simultaneously.','If the data provider relies on sub-providers, fourth-party opacity under B-10 creates exposure that current monitoring programs may not capture.']},
  {risks:[{code:'B-10',text:'Multi-vendor failure tests concentration risk — exit plans and substitutability assessments activate simultaneously'},{code:'B-13',text:'Cascading technology failures activate DR plans — scenario testing must have included this configuration to be defensible'},{code:'E-21',text:'Tests whether disruption tolerances are set realistically — BCPs must function when multiple dependencies fail at once'},{code:'E-23',text:'Model degradation during a resilience event must be within risk appetite — fallback procedures must exist'}],implications:['Institutions whose scenario testing has only covered single-point failures may be unable to demonstrate tolerance compliance during a multi-vendor stress event.','OSFI expects coordinated, cross-domain incident communication — not four separate teams sending four separate notifications about one interconnected event.']},
];
